services:
  php-apache:
    build:
      context: .
      dockerfile: ./php.dockerfile
    image: php-custom
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./www:/var/www/html
      - ./apache/httpd.conf:/etc/apache2/conf-available/docker-php.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  mariadb:
    image: mariadb:latest
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
